app/models/user.py
from flask_login import UserMixin
import json


class User(UserMixin):
    def __init__(self, user_data):
        self.id = str(user_data["_id"])  # Necessario per Flask-Login
        self.username = user_data["username"]
        self.password = user_data["password"]
        self.email = user_data["email"]
        self.name = user_data["name"]
        self.surname = user_data["surname"]
        self.favorite_albums = (
            user_data["favorite_albums"] if "favorite_albums" in user_data else []
        )
        self.following = user_data["following"] if "following" in user_data else []

    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__, sort_keys=True, indent=4)

app/routes/auth.py
from flask import Blueprint, redirect, render_template, url_for, request
from flask_login import current_user, login_user, login_required, logout_user
import bcrypt

from app.forms.auth import LoginForm, SignupForm
from app.models.user import User
from app.utils.db import get_db

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    db = get_db()
    if current_user.is_authenticated:
        return redirect(url_for("templates.index"))

    form = LoginForm()
    if form.validate_on_submit():  # Check if the form has been submitted
        email_or_username = form.email_or_username.data
        password = form.password.data
        if email_or_username is None or password is None:
            form.form_errors.append("Invalid login or password")
            return render_template("auth/login.html", form=form)

        # Check if the user exists in the database
        user = db.users.find_one(
            {"$or": [{"email": email_or_username}, {"username": email_or_username}]}
        )
        if user is None:
            form.form_errors.append("Invalid login or password")
            return render_template("auth/login.html", form=form)

        # Check if the password is correct
        hashed = user["password"]
        if not bcrypt.checkpw(password.encode("utf-8"), hashed.encode("utf-8")):
            form.form_errors.append("Invalid email or password")
            return render_template("auth/login.html", form=form)

        login_user(User(user), force=True)

        next = request.args.get("next")
        if not next:
            return redirect(url_for("templates.user", username=current_user.username))
        return redirect(next)

    return render_template("auth/login.html", form=form)


@auth.route("/signup", methods=["GET", "POST"])
def signup():
    db = get_db()
    if current_user.is_authenticated:
        return redirect(url_for("templates.index"))
    form = SignupForm()
    if form.validate_on_submit():
        data = form.data
        user = db.users.find_one({"email": data["email"]})
        if user is not None:
            form.form_errors.append("User already exists")
            return render_template("auth/signup.html", form=form)

        username = db.users.find_one({"username": data["username"]})
        if username is not None:
            form.form_errors.append("Username already taken")
            return render_template("auth/signup.html", form=form)

        hashed = bcrypt.hashpw(data["password"].encode("utf-8"), bcrypt.gensalt())
        data["password"] = hashed.decode("utf-8")
        data["favorite_albums"] = []

        _id = db.users.insert_one(
            {
                "name": data["name"],
                "surname": data["surname"],
                "username": data["username"],
                "email": data["email"],
                "password": data["password"],
                "favorite_albums": data["favorite_albums"],
            }
        ).inserted_id

        login_user(User({"_id": _id, **data}), force=True)

        next = request.args.get("next")
        if not next:
            return redirect(url_for("templates.index"))
        return redirect(next)

    return render_template("auth/signup.html", form=form)


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("templates.index"))

app/routes/templates.py
from flask import Blueprint, render_template, request, url_for
from flask_login import current_user, login_required
from flask_pymongo import ObjectId

from app.models.user import User
from app.services.music import MusicService
from app.utils.db import get_db

templates = Blueprint("templates", __name__)


@templates.route("/")
def index():
    return render_template("index.html")


@templates.route("/search")
@login_required
def search():
    query = request.args.get("q")
    page = request.args.get("page", 1)
    page = int(page)
    if page < 1:
        page = 1
    has_query = bool(query)

    pages = None
    res = None
    if has_query:
        res = MusicService.find_albums(query, page)
        total_results = int(res["totalResults"]) if "totalResults" in res else 0
        items_per_page = int(res["itemsPerPage"]) if "itemsPerPage" in res else 0
        pages = total_results // items_per_page + 1 if items_per_page > 0 else 0

    return render_template(
        "search.html",
        query=query,
        has_query=has_query,
        classname=f"{'has' if has_query else 'no'}-query",
        results=res,
        pages=pages,
        page=page,
        len=len,
    )


@templates.route("/album/<album_id>")
@login_required
def album(album_id: str):
    album = MusicService.get_album(ObjectId(album_id))
    users_with_album = MusicService.find_following_with_album(
        ObjectId(album_id), limit=4
    )

    get_username_span = (
        lambda user: f'<a href={url_for("templates.user", username=user["username"])} class="also_likes">{user["username"]}</a>'
    )

    if users_with_album is not None and len(users_with_album) == 0:
        users_with_album = None
    elif len(users_with_album) == 1:
        users_with_album = (
            f"{get_username_span(users_with_album[0])} also likes this album!"
        )
    elif len(users_with_album) == 2:
        users_with_album = f"{get_username_span(users_with_album[0])} and {get_username_span(users_with_album[1])} also like this album!"
    elif len(users_with_album) > 2:
        users_with_album = f"{', '.join([get_username_span(user) for user in users_with_album[:-1]])}, and {get_username_span(users_with_album[-1])} also like this album!"

    return render_template("album.html", album=album, users_with_album=users_with_album)


@templates.route("/user/<username>")
@login_required
def user(username: str):
    is_current_user = current_user.username == username

    user: User | None = None
    is_following = False
    followers = get_db().users.count_documents({"following": username})
    if is_current_user:
        user = User({**current_user.__dict__, "_id": ObjectId(current_user.id)})
    else:
        found = get_db().users.find_one({"username": username})
        if found is None:
            return render_template("404.html"), 404
        user = User(found)
        is_following = user.username in current_user.following

    favorite_albums = MusicService.get_albums(user.favorite_albums)

    return render_template(
        "user.html",
        user=user,
        is_current_user=is_current_user,
        is_following=is_following,
        len=len,
        followers=followers,
        favorite_albums=favorite_albums,
    )

app/templates/album.html
{% extends 'base.html' %}
{% block styles %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/album.css') }}" />
{% endblock %}
{% block title %}{{ album.name }}{% endblock %}
{% block content %}
    <main class="album_page">
        <header class="album_page_header">
            <div class="album_page_info">
                <div>
                    <h1 class="album_page_tit centerle">{{ album.name }}</h1>
                    <a href="{{ url_for("templates.search", q=album.artist) }}"
                       class="album_page_artist">{{ album.artist }}</a>
                    <a href="{{ album.url }}"
                       class="album_url"
                       target="_blank noreferrer noopener"
                       title="Listen to {{ album.name }} on Last.fm">
                        <img src="{{ url_for('static', filename='images/lastfm.svg') }}"
                             alt="Last.fm"
                             class="lastfm_icon">
                    </a>
                </div>
                <div class="album_footer" id={{ album._id }}>
                    {% if users_with_album %}<span>{{ users_with_album | safe }}</span>{% endif %}
                    <div class="album_favorite_container">
                        <button class="album_favorite"
                                {% if current_user.favorite_albums is not none and album['_id']|is_in_favorites(current_user.favorite_albums) %}data-checked="true"{% endif %}
                                onclick="toggleFavorite('{{ album['_id'] }}')"></button>
                        <p class="search_result_stars">
                            {% if 'stars' in album %}
                                {{ album['stars'] }}
                            {% else %}
                                0
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
            <img src="{{ album.image[3]['#text'] }}"
                 alt="Album cover"
                 class="album_cover"
                 draggable="false">
        </header>
        <div class="tracks">
            <table class="tracks_table">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Duration</th>
                        <th>
                            <!-- Last.fm button -->
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for track in album.tracks.track %}
                        <tr>
                            <td>{{ loop.index }}</td>
                            <td>{{ track.name }}</td>
                            {% if track.duration %}
                                <td>{{ track.duration|seconds_to_time_string }}</td>
                            {% else %}
                                <td>Unknown</td>
                            {% endif %}
                            {% if track.url %}
                                <td>
                                    <a href="{{ track.url }}"
                                       title="Open &quot;{{ track.name }}&quot; on Last.fm">
                                        <img src="{{ url_for('static', filename='images/lastfm.svg') }}"
                                             alt="Last.fm"
                                             class="lastfm_icon">
                                    </a>
                                </td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% if album.wiki %}
            <section class="album_wiki">
                <h2>Wiki</h2>
                <p>{{ album.wiki.content | safe }}</p>
            </section>
        {% endif %}
    </header>
</main>
{% endblock %}
{% block scripts %}<script src="{{ url_for('static', filename='js/search.js') }}"></script>{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>
            {% block title %}{% endblock %}
        - NoteInvader</title>
        <link rel="shortcut icon"
              href="{{ url_for('static', filename='favicon.ico') }}" />
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/utils/fonts.css') }}" />
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/utils/reset.css') }}" />
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/utils/colors.css') }}" />
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/base.css') }}" />
        {% block styles %}{% endblock %}
    </head>
    <body>
        <a class="floating_button" href="{{ url_for("templates.search") }}">
            <img alt="search"
                 class="floating_button_icon"
                 src="{{ url_for('static', filename='images/search.svg') }}" />
        </a>
        {% if request.endpoint not in endpoints_with_no_navbar %}
            <nav id="navigation_bar" class="navbar">
                <a href="/" title="NoteInvader">
                    <img alt="logo"
                         class="navbar_logo"
                         src="{{ url_for('static', filename='logo.svg') }}" />
                </a>
                {% if current_user.is_authenticated %}
                    <form class="navbar_search"
                          action="{{ url_for("templates.search") }}"
                          method="get">
                        <input class="navbar_search_input"
                               id="navbar_search_input"
                               type="text"
                               name="q"
                               placeholder="Search for some music..."
                               required
                               onkeyup="syncSearchBoxes(true)"
                               value="{% if request.endpoint =='templates.search' and query %}{{ query }}{% endif %}" />
                        <button class="navbar_search_button" type="submit">
                            <img alt="search"
                                 class="navbar_search_icon"
                                 src="{{ url_for('static', filename='images/search.svg') }}" />
                        </button>
                    </form>
                {% endif %}
                <div class="navbar_links">
                    {% if current_user.is_authenticated %}<p class="greeter">Hello, {{ current_user.name }}!</p>{% endif %}
                    <a class="navbar_link" href="/">Home</a>
                    {% if current_user.is_authenticated %}
                        <a class="navbar_link"
                           href="{{ url_for("templates.user",username=current_user.username) }}">Profile</a>
                        <a class="navbar_link" href="{{ url_for("auth.logout") }}">Logout</a>
                        <a href="{{ url_for("templates.user",username=current_user.username) }}">
                            <img class="navbar_link_icon"
                                 src="{{ url_for('static', filename='images/user.svg') }}"
                                 alt="profile" />
                        </a>
                        <a href="{{ url_for("auth.logout") }}">
                            <img class="navbar_link_icon"
                                 src="{{ url_for('static', filename='images/logout.svg') }}"
                                 alt="logout" />
                        </a>
                    {% else %}
                        <a class="navbar_link" href="{{ url_for("auth.login") }}">Login</a>
                        <a href="{{ url_for("auth.login") }}">
                            <img class="navbar_link_icon"
                                 src="{{ url_for('static', filename='images/login.svg') }}"
                                 alt="login" />
                            <a class="navbar_link" href="{{ url_for("auth.signup") }}">Signup</a>
                            <a href="{{ url_for("auth.signup") }}">
                                <img class="navbar_link_icon"
                                     src="{{ url_for('static', filename='images/signup.svg') }}"
                                     alt="signup" />
                            </a>
                        {% endif %}
                    </div>
                </nav>
            {% endif %}
            {% block content %}{% endblock %}
            {% block scripts %}{% endblock %}
            <script src="{{ url_for('static', filename='js/base.js') }}"></script>
        </body>
    </html>

app/templates/index.html
{% extends 'base.html' %}
{% block styles %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/index.css') }}" />
{% endblock %}
{% block title %}Home{% endblock %}
{% block content %}
    <main class="home_screen">
        <header class="header">
            <img src="{{ url_for('static', filename='logo.svg') }}" />
            <h1>Enjoy your music with others!</h1>
            <p>
                Welcome to NoteInvader!
                <br />
                Here, you can add your own album collection and snoop around on your friends' collections!
            </p>
            {% if current_user.is_authenticated %}
                <a class="header_link login" href="{{ url_for("templates.search") }}">Search for music</a>
            {% else %}
                <div class="header_links">
                    <a class="header_link login" href="{{ url_for("auth.login") }}">Login</a>
                    <a class="header_link register" href="{{ url_for("auth.signup") }}">Signup</a>
                </div>
            {% endif %}
        </header>
    </main>
{% endblock %}

app/templates/search.html
{% extends 'base.html' %}
{% block styles %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/search.css') }}" />
{% endblock %}
{% block title %}Search{% endblock %}
{% block content %}
    <main class='search_page {{ classname }}'>
        {% if not has_query %}
            <h1>Search for an album or an artist</h1>
            <form class="search_form"
                  action="{{ url_for("templates.search") }}"
                  method="get">
                <input class="search_input"
                       id="search_input"
                       type="text"
                       name="q"
                       placeholder="Search here..."
                       required
                       onkeyup="syncSearchBoxes(false)"
                       value="{% if query %}{{ query }}{% endif %}" />
                <button class="search_button" type="submit">
                    <img alt="search"
                         class="search_icon"
                         src="{{ url_for('static', filename='images/search.svg') }}" />
                </button>
            </form>
        {% endif %}
        {% if has_query %}
            {% if len(results['albummatches']) == 0 %}
                <p class="no_results">
                    No results found for <span class="query_reminder">{{ query }}</span>
                </p>
            {% else %}
                <h1>
                    Search results for <span class="query_reminder">{{ query }}</span>
                </h1>
                <div id="results" class="search_results">
                    {% for album in results['albummatches'] %}
                        <div class="search_result" id="{{ album['_id'] }}">
                            <a href="{{ url_for('templates.album', album_id=album['_id']) }}"
                               class="search_result_title">
                                {% if album['image'][3]['#text'] %}
                                    <img class="search_result_image"
                                         src="{{ album['image'][3]['#text'] }}"
                                         alt="{{ album['name'] }}"
                                         onerror="this.src='{{ url_for('static', filename='images/not-found.webp') }}'; this.onerror=null;" />
                                {% else %}
                                    <img class="search_result_image"
                                         src="{{ url_for('static', filename='images/not-found.webp') }}"
                                         alt="{{ album['name'] }}" />
                                {% endif %}
                            </a>
                            <div class="search_result_info">
                                <div class="search_result_artist_title">
                                    <a href="{{ url_for('templates.album', album_id=album['_id']) }}"
                                       class="search_result_title">{{ album['name'] }}</a>
                                    <p class="search_result_artist">{{ album['artist'] }}</p>
                                </div>
                                <div class="search_result_footer">
                                    <button class="search_result_favorite"
                                            {% if current_user.favorite_albums is not none and album['_id']|is_in_favorites(current_user.favorite_albums) %}data-checked="true"{% endif %}
                                            onclick="toggleFavorite('{{ album['_id'] }}')"></button>
                                    <p class="search_result_stars">
                                        {% if 'stars' in album %}
                                            {{ album['stars'] }}
                                        {% else %}
                                            0
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                {% if pages > 1 %}
                    <div class="page_navigation">
                        <button class="page_navigation_button"
                                onClick="goToPage({{ page - 1 }})"
                                {% if page == 1 %}disabled{% endif %}>Previous</button>
                        <p class="page_navigation_info">Page {{ page }} of {{ pages }}</p>
                        <button class="page_navigation_button"
                                onClick="goToPage({{ page + 1 }})"
                                {% if page == pages %}disabled{% endif %}>Next</button>
                    </div>
                {% endif %}
            {% endif %}
        {% endif %}
    </main>
{% endblock %}
{% block scripts %}<script src="{{ url_for('static', filename='js/search.js') }}"></script>{% endblock %}

app/templates/user.html
{% extends 'base.html' %}
{% block styles %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/user.css') }}" />
{% endblock %}
{% block title %}{{ user.username }}{% endblock %}
{% block content %}
    <main class="user_screen">
        <header class="header">
            <img src="https://images.unsplash.com/photo-1640951613773-54706e06851d?q=80&w=880&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                 alt="{{ user.username }}'s profile picture"
                 class="profile_picture" />
            <div class="user_info">
                <h1 class="user_name">
                    {{ user.name }} <span class="surname">{{ user.surname }}</span>
                </h1>
                <p class="user_username">@{{ user.username }}</p>
                <div class="actions">
                    <div class="stats">
                        <img class="followers_icon"
                             src="{{ url_for("static", filename="/images/user.svg") }}" />
                        <p class="stat_number">
                            <span class="followers"
                                  id="followers_number"
                                  title="{{ followers }} {% if followers != 1 %}followers{% else %}follower{% endif %} ">{{ followers|compact_number }}
                            </span>
                            {% if followers != 1 %}
                                followers
                            {% else %}
                                follower
                            {% endif %}
                        </p>
                    </div>
                    {% if not is_current_user %}
                        <button onclick="toggleFollow('{{ user.username }}')"
                                id="follow_button"
                                class="header_link {% if is_following %}unfollow{% endif %}">
                            {% if is_following %}
                                Unfollow
                            {% else %}
                                Follow
                            {% endif %}
                        </button>
                    {% endif %}
                </div>
            </div>
            <form id="user_search"
                  class="search"
                  onsubmit="handleSubmit(); return false;">
                <input class="search_input"
                       id="user_search_input"
                       type="text"
                       name="username"
                       placeholder="Search for a user..."
                       required />
                <button class="search_button" type="submit">
                    <img alt="search"
                         class="search_icon"
                         src="{{ url_for('static', filename='images/search.svg') }}" />
                </button>
            </form>
        </header>
        <div class="albums">
            <h2 class="albums_title">
                {% if is_current_user %}
                    Your favorite albums
                {% else %}
                    {{ user.username }}'s favorite albums
                {% endif %}
            </h2>
            <div class="albums_grid">
                {% for album in favorite_albums %}
                    <div class="album" id={{ album['_id'] }}>
                        <img src="{{ album.image[3]['#text'] }}"
                             alt="{{ album.name }}"
                             class="album_cover" />
                        <div class="album_overlay">
                            <a href="{{ url_for("templates.album", album_id=album['_id']) }}"
                               class="album_overlay_link"></a>
                            <div class="album_info">
                                <div class="album_title_and_artist">
                                    <p class="album_title">{{ album.name }}</p>
                                    <p class="album_artist">{{ album.artist }}</p>
                                </div>
                                {% if is_current_user %}
                                    <button class="album_favorite"
                                            {% if current_user.favorite_albums is not none and album['_id']|is_in_favorites(current_user.favorite_albums) %}data-checked="true"{% endif %}
                                            onclick="toggleFavorite('{{ album['_id'] }}')"></button>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock %}
{% block scripts %}<script src="{{ url_for('static', filename='js/user.js') }}"></script>{% endblock %}